version: '2'
services:
  postgres:
    image: "jas/postgres:${VERSION}"
    build:
      context: .
      dockerfile: postgres.Dockerfile
    expose: [ "5432" ]
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      jasnet:
        ipv4_address: 172.25.0.2
    volumes:
      - jas_pgdata:/var/lib/postgresql/data
  server:
    depends_on:
      - postgres
    image: "jas/server:${VERSION}"
    build:
      context: .
      dockerfile: server.Dockerfile
    expose: [ "8080" ]
    environment:
      JAS_PORT: 8080
      JAS_DB_HOST: 172.25.0.2
      JAS_DB_NAME: "${JAS_DB_NAME}"
      JAS_DB_USER: "${JAS_DB_USER}"
      JAS_DB_PASS: "${JAS_DB_PASS}"
      JAS_DB_PORT: "${JAS_DB_PORT}"
      JAS_TOKEN_SIGN: "${JAS_TOKEN_SIGN}"
      JAS_TOKEN_ALGO: "${JAS_TOKEN_ALGO}"
      JAS_TOKEN_EXP: "${JAS_TOKEN_EXP}"
    networks:
      jasnet:
        ipv4_address: 172.25.0.4
networks:
  jasnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/16
volumes:
  jas_pgdata:
